/**
 * Public service catalog used by Popular Data Services and generated examples.
 * Keep uncertain terms explicit and leave lastChecked null until validation runs.
 */
export const POPULAR_SERVICES = [
  {
    id: "usgs-naip-plus", slug: "usgs-naip-imagery", provider: "USGS",
    title: "USGS NAIP Plus", category: "Satellite / imagery", serviceType: "imagery",
    description: "National Agriculture Imagery Program imagery served by The National Map.",
    whyUseful: "Inspect recent high-resolution aerial imagery across supported areas of the United States in a 3D scene.",
    url: "https://imagery.nationalmap.gov/arcgis/rest/services/USGSNAIPPlus/ImageServer",
    sourceOrganization: "U.S. Geological Survey — The National Map",
    sourcePage: "https://www.usgs.gov/programs/national-geospatial-program/national-map",
    licenseOrTerms: "U.S. Geological Survey source; review source metadata and USGS usage guidance.",
    tags: ["USGS", "NAIP", "aerial imagery", "ImageServer", "United States"],
    lastChecked: null, featured: true,
  },
  {
    id: "esri-modis-hotspots-recent", slug: "modis-active-fires", provider: "Esri Disaster Response",
    title: "Recent MODIS Hotspot Data", category: "Wildfires", serviceType: "feature",
    description: "Recent thermal anomalies detected by the MODIS satellite instruments.",
    whyUseful: "Explore recent satellite-detected thermal anomalies and compare their distribution with terrain, communities, and other public layers.",
    url: "https://services9.arcgis.com/RHVPKKiFTONKtxq3/arcgis/rest/services/MODIS_Thermal_v1/FeatureServer/0",
    sourceOrganization: "Esri Disaster Response Program",
    sourcePage: "https://services9.arcgis.com/RHVPKKiFTONKtxq3/arcgis/rest/services/MODIS_Thermal_v1/FeatureServer/0",
    licenseOrTerms: "Review the service metadata and publisher terms before reuse.",
    tags: ["MODIS", "wildfire", "thermal anomaly", "satellite", "FeatureServer"],
    lastChecked: null, featured: true,
  },
  {
    id: "esri-active-hurricanes", slug: "active-hurricanes", provider: "Esri Disaster Response",
    title: "Active Hurricanes", category: "Weather", serviceType: "feature",
    description: "Current tropical cyclone tracks, forecasts, and related observations.",
    whyUseful: "View the multiple forecast, track, warning, and wind-field layers commonly published for active tropical systems.",
    url: "https://services9.arcgis.com/RHVPKKiFTONKtxq3/ArcGIS/rest/services/Active_Hurricanes_v1/FeatureServer",
    sourceOrganization: "Esri Disaster Response Program",
    sourcePage: "https://services9.arcgis.com/RHVPKKiFTONKtxq3/ArcGIS/rest/services/Active_Hurricanes_v1/FeatureServer",
    licenseOrTerms: "Review the service metadata and publisher terms before reuse.",
    tags: ["hurricane", "tropical cyclone", "forecast", "weather", "FeatureServer"],
    lastChecked: null, featured: false,
  },
  {
    id: "esri-air-quality-pm25", slug: "air-quality-pm25", provider: "Esri Disaster Response",
    title: "PM2.5 Data", category: "Environment", serviceType: "feature",
    description: "Latest particulate matter air-quality observations and results.",
    whyUseful: "Inspect recent PM2.5 measurements and their attributes alongside communities, terrain, and other environmental layers.",
    url: "https://services9.arcgis.com/RHVPKKiFTONKtxq3/ArcGIS/rest/services/Air_Quality_PM25_Latest_Results/FeatureServer",
    sourceOrganization: "Esri Disaster Response Program",
    sourcePage: "https://services9.arcgis.com/RHVPKKiFTONKtxq3/ArcGIS/rest/services/Air_Quality_PM25_Latest_Results/FeatureServer",
    licenseOrTerms: "Review individual provider fields, service metadata, and publisher terms before reuse.",
    tags: ["PM2.5", "air quality", "environment", "sensors", "FeatureServer"],
    lastChecked: null, featured: true,
  },
  {
    id: "esri-usgs-seismic-activity", slug: "usgs-seismic-activity", provider: "USGS / Esri",
    title: "USGS Seismic Activity", category: "Earthquakes", serviceType: "feature",
    description: "Recent earthquake and seismic activity reported by the USGS.",
    whyUseful: "Explore recent seismic events as queryable ArcGIS feature layers.",
    url: "https://services9.arcgis.com/RHVPKKiFTONKtxq3/ArcGIS/rest/services/USGS_Seismic_Data_v1/FeatureServer",
    sourceOrganization: "U.S. Geological Survey / Esri",
    sourcePage: "https://services9.arcgis.com/RHVPKKiFTONKtxq3/ArcGIS/rest/services/USGS_Seismic_Data_v1/FeatureServer",
    licenseOrTerms: "Review the service metadata, USGS source guidance, and publisher terms.",
    tags: ["USGS", "earthquake", "seismic", "hazards", "FeatureServer"],
    lastChecked: null, featured: false,
  },
  {
    id: "usgs-recent-earthquakes-map", slug: "usgs-recent-earthquakes-map-service", provider: "USGS",
    title: "USGS Recent Earthquakes Map Service", category: "Earthquakes", serviceType: "map-image",
    description: "A USGS ArcGIS MapServer presenting recent earthquake activity.",
    whyUseful: "Compare a rendered ArcGIS MapServer with queryable feature and GeoJSON earthquake sources.",
    url: "https://earthquake.usgs.gov/arcgis/rest/services/eq/Recent_Earthquakes/MapServer",
    sourceOrganization: "U.S. Geological Survey — Earthquake Hazards Program",
    sourcePage: "https://earthquake.usgs.gov/arcgis/rest/services/eq/Recent_Earthquakes/MapServer",
    licenseOrTerms: "U.S. Geological Survey source; review service metadata and USGS usage guidance.",
    tags: ["USGS", "earthquake", "MapServer", "hazards"],
    lastChecked: null, featured: false,
  },
  {
    id: "esri-ndfd-wind-gusts", slug: "ndfd-wind-gusts", provider: "NWS / Esri",
    title: "NDFD Wind Gusts", category: "Weather", serviceType: "feature",
    description: "Forecast wind-gust conditions from the National Digital Forecast Database.",
    whyUseful: "Explore forecast wind-gust values spatially and inspect their time-related attributes.",
    url: "https://services9.arcgis.com/RHVPKKiFTONKtxq3/ArcGIS/rest/services/NDFD_WindGust_v1/FeatureServer",
    sourceOrganization: "National Weather Service / Esri",
    sourcePage: "https://services9.arcgis.com/RHVPKKiFTONKtxq3/ArcGIS/rest/services/NDFD_WindGust_v1/FeatureServer",
    licenseOrTerms: "Review the service metadata and publisher terms before reuse.",
    tags: ["NDFD", "wind gust", "forecast", "weather", "FeatureServer"],
    lastChecked: null, featured: false,
  },
  {
    id: "esri-ndfd-precipitation", slug: "ndfd-precipitation", provider: "NWS / Esri",
    title: "NDFD Precipitation", category: "Weather", serviceType: "feature",
    description: "Forecast precipitation from the National Digital Forecast Database.",
    whyUseful: "Inspect forecast precipitation values and compare them with other environmental or infrastructure data.",
    url: "https://services9.arcgis.com/RHVPKKiFTONKtxq3/ArcGIS/rest/services/NDFD_Precipitation_v1/FeatureServer",
    sourceOrganization: "National Weather Service / Esri",
    sourcePage: "https://services9.arcgis.com/RHVPKKiFTONKtxq3/ArcGIS/rest/services/NDFD_Precipitation_v1/FeatureServer",
    licenseOrTerms: "Review the service metadata and publisher terms before reuse.",
    tags: ["NDFD", "precipitation", "forecast", "weather", "FeatureServer"],
    lastChecked: null, featured: false,
  },
  {
    id: "usgs-earthquakes-month", slug: "usgs-earthquakes", provider: "USGS",
    title: "Earthquakes — past 30 days", category: "Earthquakes", serviceType: "geojson",
    description: "Continuously updated GeoJSON feed of global earthquake activity.",
    whyUseful: "Explore a live global point feed, inspect magnitude and event attributes, filter records, and export selected data.",
    url: "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_month.geojson",
    sourceOrganization: "U.S. Geological Survey — Earthquake Hazards Program",
    sourcePage: "https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php",
    licenseOrTerms: "U.S. Geological Survey source; follow the linked feed policy and USGS usage guidance.",
    tags: ["USGS", "earthquake", "GeoJSON", "live feed", "global"],
    lastChecked: null, featured: true, refreshInterval: 5,
  },
  {
    id: "esri-world-countries", slug: "world-countries-generalized", provider: "Esri",
    title: "World countries — generalized", category: "Census / demographics", serviceType: "feature",
    description: "Generalized country boundaries from an ArcGIS feature service.",
    whyUseful: "Use lightweight country polygons as geographic context or as a simple FeatureServer example.",
    url: "https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/World_Countries_(Generalized)/FeatureServer/0",
    sourceOrganization: "Esri",
    sourcePage: "https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/World_Countries_(Generalized)/FeatureServer/0",
    licenseOrTerms: "Review the service item, metadata, and Esri terms before reuse.",
    tags: ["countries", "boundaries", "world", "FeatureServer"],
    lastChecked: null, featured: false,
  },
];

export const EXAMPLE_CATEGORIES = [
  "Wildfires", "Earthquakes", "Weather", "Transportation",
  "Census / demographics", "Satellite / imagery", "Environment", "Public infrastructure",
];
