import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const html = await readFile(new URL("../index.html", import.meta.url), "utf8");
const ui = await readFile(new URL("../js/ui.js", import.meta.url), "utf8");
const robots = await readFile(new URL("../robots.txt", import.meta.url), "utf8");
const sitemap = await readFile(new URL("../sitemap.xml", import.meta.url), "utf8");

assert.match(html, /<title>GIS Map Online — Free 3D ArcGIS REST &amp; GeoJSON Viewer<\/title>/);
assert.match(html, /<link rel="canonical" href="https:\/\/gismap\.online\/" \/>/);
assert.match(html, /property="og:image"/);
assert.match(html, /name="twitter:card" content="summary_large_image"/);
assert.match(html, /<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
const structuredData = JSON.parse(html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)[1]);
assert.deepEqual(structuredData["@type"], ["SoftwareApplication", "WebApplication"]);
assert.equal(structuredData.isAccessibleForFree, true);
assert.equal(structuredData.author.name, "Silas Toms");
assert.match(html, /id="welcome-title">Explore GIS data instantly/);
assert.match(html, /id="welcome-close"[^>]*aria-label="Dismiss introduction"/);
assert.doesNotMatch(ui, /welcomePanel\.hidden\s*=\s*Boolean\(layers\.length\)/);
assert.match(ui, /button\.closest\("#welcome-panel"\)/);
assert.match(ui, /if \(open\) this\.#dismissWelcome\(\)/);
assert.match(ui, /if \(layers\.length\) this\.#dismissWelcome\(\)/);
assert.doesNotMatch(ui, /WELCOME_DISMISSED_KEY|sessionStorage/);
assert.match(ui, /data-ai-selection/);
assert.match(ui, /selectedResults/);
assert.match(html, /id="insights-ai"[^>]*title="AI Insights"/);
assert.match(html, /id="utility-tabs"/);
assert.match(html, /class="mobile-map-brand"[^>]*gis-map-online-mark-v2/);
assert.match(html, /id="mobile-map-tools-toggle"/);
assert.match(html, /id="mobile-drawer-handle"/);
assert.match(html, /id="mobile-project-toggle"/);
assert.match(html, /data-mobile-panel="intelligence-panel"[^>]*aria-label="Location intelligence"/);
assert.match(html, /aria-label="Mobile tool drawer"/);
assert.match(ui, /#bindMobileDrawerGesture/);
assert.match(ui, /mobileDrawerContent\.inert/);
assert.match(html, /data-widget="legend">Legend/);
assert.match(html, /id="draw-workspace-open"/);
assert.match(html, /data-utility-pane="style"/);
assert.match(ui, /#openDrawUtility/);
assert.match(ui, /#openSymbologyUtility/);
assert.match(ui, /lastAIResponseText/);
assert.match(ui, /Open in right panel/);
assert.match(ui, /navigationLayout === "top"\) this\.#openIntelligenceUtility/);
assert.match(ui, /intelligencePanel\.hidden = true/);
assert.match(ui, /querySelector\("#intelligence-panel"\)\.hidden = false/);
assert.match(ui, /lastAIQueryText/);
assert.match(ui, /goToFeature\(result\)/);
assert.match(ui, /Selected data query/);
assert.match(ui, /data-close-utility-tab/);
assert.match(robots, /Sitemap: https:\/\/gismap\.online\/sitemap\.xml/);
assert.match(sitemap, /<loc>https:\/\/gismap\.online\/<\/loc>/);
